services:
  backend1:
    image: hashicorp/http-echo:latest
    command: ["-text=Backend 1"]
    ports:
      - "8081:5678"

  backend2:
    image: hashicorp/http-echo:latest
    command: ["-text=Backend 2"]
    ports:
      - "8082:5678"

  backend3:
    image: hashicorp/http-echo:latest
    command: ["-text=Backend 3"]
    ports:
      - "8083:5678"

  balancer:
    build: ../
    ports:
      - "1234:1234"
    environment:
      - PORT=1234
      - BACKENDS=http://backend1:5678,http://backend2:5678,http://backend3:5678
    depends_on:
      - backend1
      - backend2
      - backend3
